debug:
  path: plugins/BungeePerms/debug.log
  showexceptions: true
  showlogs: false
bungeeperms:
  general:
    mysqlhost: localhost
    mysqlport: '3306'
    mysqldb: bungeeperms
    mysqluser: bungeeperms
    mysqlpw: password
backendtype: YAML
tablePrefix: bungeeperms_
uuidplayerdb: YAML
useUUIDs: true
saveAllUsers: true
deleteUsersOnCleanup: false
